version: '3'

volumes:
  devpi:

services:
  devpi:
    image: lecovi/devpi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3142:3141"
    volumes:
      - devpi:/root/.devpi/server