version: '3'

volumes:
  devpi:
  bandersnatch:

services:
  devpi:
    image: lecovi/devpi
    build:
      context: devpi
      dockerfile: Dockerfile
    ports:
      - "3141:3141"
    volumes:
      - devpi:/root/.devpi/server

  banderx:
    image: lecovi/banderx
    build:
      context: banderx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - bandersnatch:/data/pypi/mirror

  bandersnatch:
    image: lecovi/bandersnatch
    build:
      context: bandersnatch
      dockerfile: Dockerfile
    volumes:
      - bandersnatch:/data/pypi/mirror
      - ./bandersnatch/bandersnatch.conf:/etc/bandersnatch.conf
